services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dunamys-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=5000
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres123}@postgres:5432/${POSTGRES_DB:-igreja_membros}?schema=public
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - FRONTEND_URL=${FRONTEND_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - MASTER_ADMIN_EMAIL=${MASTER_ADMIN_EMAIL}
      - WHATSAPP_ENABLED=${WHATSAPP_ENABLED:-true}
      - WHATSAPP_SERVICE_URL=http://whatsapp:3000
    volumes:
      - ./backend/logs:/app/logs
      - ./backend/whatsapp-session:/app/whatsapp-session
      - ./backend/uploads:/app/uploads
    depends_on:
      - postgres
      - redis
    networks:
      - dunamys-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${API_URL}
        VITE_MASTER_ADMIN_EMAIL: ${MASTER_ADMIN_EMAIL}
    container_name: dunamys-frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - dunamys-network

  nginx:
    image: nginx:alpine
    container_name: dunamys-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - dunamys-network

  postgres:
    image: postgres:15-alpine
    container_name: dunamys-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-igreja_membros}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres123}
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/prisma/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    networks:
      - dunamys-network

  redis:
    image: redis:7-alpine
    container_name: dunamys-redis
    restart: unless-stopped
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data
    networks:
      - dunamys-network

  whatsapp:
    build:
      context: ./backend/whatsapp
      dockerfile: Dockerfile
    container_name: dunamys-whatsapp
    restart: unless-stopped
    # ports:
    #   - "3000:3000"  # Comentado - só acessível internamente
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=3000
    volumes:
      - whatsapp_session:/app/whatsapp-session
      - whatsapp_temp:/app/temp
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    mem_limit: 2g
    depends_on:
      - redis
    networks:
      - dunamys-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  whatsapp_session:
    driver: local
  whatsapp_temp:
    driver: local

networks:
  dunamys-network:
    driver: bridge