services:
  postgres:
    image: postgres:15-alpine
    container_name: igreja-postgres
    environment:
      POSTGRES_DB: igreja_membros
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - igreja-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: igreja-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - igreja-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  igreja-network:
    driver: bridge