services:
  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dunamys-frontend
    ports:
      - "3002:80"
    environment:
      - VITE_API_URL=http://localhost:4002
    depends_on:
      - backend
    networks:
      - dunamys-network
    restart: unless-stopped

  # Backend API  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dunamys-backend
    ports:
      - "4002:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_URL=postgresql://postgres:postgres123@postgres:5432/igreja_membros?schema=public
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FRONTEND_URL=http://localhost:3002
      - JWT_SECRET=sua_chave_secreta_super_forte_aqui
      - JWT_EXPIRES_IN=7d
      - LOG_LEVEL=info
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend/logs:/app/logs
      - ./backend/whatsapp-session:/app/whatsapp-session
    networks:
      - dunamys-network
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: dunamys-postgres
    environment:
      POSTGRES_DB: igreja_membros
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dunamys-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: dunamys-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - dunamys-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  dunamys-network:
    driver: bridge