export const API_BASE_URL = '/api';

export const USER_ROLES = {
    ADMIN: 'ADMIN',
    MEMBER: 'MEMBER'
};

export const USER_STATUS = {
    PENDING: 'PENDING',
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
    REJECTED: 'REJECTED'
};

export const NOTIFICATION_TYPES = {
    SCHEDULE_ASSIGNMENT: 'SCHEDULE_ASSIGNMENT',
    SCHEDULE_UPDATE: 'SCHEDULE_UPDATE',
    SCHEDULE_CANCELLATION: 'SCHEDULE_CANCELLATION',
    SCHEDULE_REMINDER: 'SCHEDULE_REMINDER',
    CUSTOM_NOTIFICATION: 'CUSTOM_NOTIFICATION'
};

export const DATE_FORMATS = {
    DATE: 'dd/MM/yyyy',
    DATETIME: "dd/MM/yyyy 'às' HH:mm",
    TIME: 'HH:mm'
};